[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "govbidgenie"
version = "0.1.0"
description = "A lead generation and management tool."
readme = "README.md"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["backend"] 