"""Add source to Lead model

Revision ID: a79f8838e0c0
Revises: 
Create Date: 2025-06-26 22:13:38.897728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a79f8838e0c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('source', sa.String(), nullable=True))
    op.drop_column('leads', 'analyzed_for_learning')
    op.drop_column('leads', 'facebook_page_url')
    op.drop_column('leads', 'business_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('business_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('facebook_page_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('analyzed_for_learning', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('leads', 'source')
    # ### end Alembic commands ###
