"""add business_name and facebook_page_url to lead model

Revision ID: 0b20a09d8c71
Revises: a79f8838e0c0
Create Date: 2025-06-27 02:16:21.050386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b20a09d8c71'
down_revision: Union[str, Sequence[str], None] = 'a79f8838e0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('business_name', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('facebook_page_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'facebook_page_url')
    op.drop_column('leads', 'business_name')
    # ### end Alembic commands ###
