"""Add analyzed_for_learning to Lead model

Revision ID: 585dd5492e57
Revises: ffb3d113b6fe
Create Date: 2025-07-03 16:03:17.519507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585dd5492e57'
down_revision: Union[str, Sequence[str], None] = 'ffb3d113b6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('external_event_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outcome_tag', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('NAICS_Codes')
    op.add_column('leads', sa.Column('analyzed_for_learning', sa.Boolean(), nullable=True))
    op.drop_column('leads', 'source')
    op.add_column('opportunities', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('location_text', sa.String(length=255), nullable=True))
    op.drop_column('opportunities', 'psc_code')
    op.drop_column('opportunities', 'naics_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('naics_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('psc_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('opportunities', 'location_text')
    op.drop_column('opportunities', 'description')
    op.add_column('leads', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('leads', 'analyzed_for_learning')
    op.create_table('NAICS_Codes',
    sa.Column('code', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('NAICS_Codes_pkey'))
    )
    op.drop_table('learnings')
    op.drop_table('conversation_logs')
    op.drop_table('appointments')
    # ### end Alembic commands ###
